CREATE DATABASE IF NOT EXISTS exam
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'exam'@'localhost' IDENTIFIED BY 'pnZEx6hiXTCkNCJ8';
ALTER USER 'exam'@'localhost' IDENTIFIED BY 'pnZEx6hiXTCkNCJ8';

CREATE USER IF NOT EXISTS 'exam'@'127.0.0.1' IDENTIFIED BY 'pnZEx6hiXTCkNCJ8';
ALTER USER 'exam'@'127.0.0.1' IDENTIFIED BY 'pnZEx6hiXTCkNCJ8';

GRANT ALL PRIVILEGES ON exam.* TO 'exam'@'localhost';
GRANT ALL PRIVILEGES ON exam.* TO 'exam'@'127.0.0.1';

FLUSH PRIVILEGES;
